IP_NETWORK="192.168.69."
WORKSTATION_IP=10

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.ssh.insert_key = false
  config.vm.network "private_network", ip: IP_NETWORK + "#{WORKSTATION_IP}"
  config.vm.provider "virtualbox" do |vb|
    # vb.gui = true
    vb.memory = "2048"
    vb.cpus = 2
  end
end
